# -*- coding: utf-8 -*-
"""POLINESIOS (trabajo final)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8A0mZ3P4JBOG2AXYDc2bJepQXqxKMok
"""

from PIL import Image

# Abre la imagen indicando la ruta del archivo
imagen_karen = Image.open("/karenpolinesio.jpg")

from PIL import Image

# Abre la imagen indicando la ruta del archivo
imagen_leslie = Image.open("/lesliepolinesia.jpg")

#Hacemos una función para validar que las respuestas sí sean del 1 al 3
def pedir_respuesta():
  while True:
    try:
      respuesta = int(input("Elige un número:"))
      if respuesta in [1, 2, 3]:
        return respuesta
      else:
        print("Por favor, ingresa solo 1, 2 o 3.")
    except ValueError:
      print("Respuesta no válida. Debes ingresar un número del 1 al 3")

# Presentación del test:
print("¡Hola Polinesios!¿Cómo están? Bienvenidos al PoliTest, donde descubrirás qué polinesio eres en base a tu personalidad :)")

#Pregunta 1 y sus alternativas:
print("1) ¿Cuál es tu color favorito?")
print("1. Verde")
print("2. Morado")
print("3. Rosado")
p1 = pedir_respuesta()

#Pregunta 2 y sus alternativas:
print("2) ¿Te consideras una persona sensible?")
print("1. De vez en cuando")
print("2. No")
print("3. Sí")
p2 = pedir_respuesta()

##Pregunta 3 y sus alternativas:
print("3) ¿Quién te consideras en tu grupo de amigos?")
print("1. El funable")
print("2. El directo o consejero")
print("3. El cariñoso")
p3 = pedir_respuesta()

#Pregunta 4 y sus alternativas:
print("4) ¿Qué prefieres hacer en tu cumpleaños?")
print("1. Ir de viaje")
print("2. Planificar con tiempo lo que deseo")
print("3. Sorpresa preparada por mis seres queridos")
p4 = pedir_respuesta()

#Pregunta 5 y sus alternativas:
print("5) Si pudieras vivir en uno de los siguientes países ¿cuál sería?")
print("1. Japón")
print("2. Inglaterra")
print("3. Estados Unidos")
p5 = pedir_respuesta()

#Pregunta 6 y sus alternativas:
print("6) ¿Qué tipo de slime prefieres?")
print("1. De detergente")
print("2. De crema para afeitar")
print("3. De detergente")
p6 = pedir_respuesta()

#Pregunta 7 y sus alternativas:
print("7) ¿Te gustaría tener hijos?")
print("1. Sí, con una gran familia")
print("2. No lo tengo entre mis planes")
print("3. Sí, una familia tradicional")
p7 = pedir_respuesta()

#Pregunta 8 y sus alternativas:
print("8) ¿Qué películas prefieres ver?")
print("1. Comedia")
print("2. Terror")
print("3. Drama romántico")
p8 = pedir_respuesta()

#Pregunta 9 y sus alternativas:
print("9) En el salón de clases ¿Quién eres?")
print("1. El payaso")
print("2. El dormilón")
print("3. El aplicado")
p9 = pedir_respuesta()

#Pregunta 10 y sus alternativas:
print("10) ¿Alguna vez te has obsesionado tanto con una canción que la cantas por semanas?")
print("1. Solo con canciones en específico")
print("2. No")
print("3. Sí, siempre me sucede")
p10 = pedir_respuesta()

#Pregunta 11 y sus alternativas:
print("11) ¿Qué rol tomas en los viajes?")
print("1. Quién busca actividades para divertirse")
print("2. Quien solo se guía por sus acompañantes")
print("3. Quien organiza el itinerario y presupuestos")
p11 = pedir_respuesta()

#Pregunta 12 y sus alternativas:
print("12) ¿Qué regalo prefieres recibir?")
print("1. Algo inesperado y gracioso")
print("2. Algo útil")
print("3. Algo significativo y sentimental")
p12 = pedir_respuesta()

#Pregunta 13 y sus alternativas:
print("13) ¿Qué haces cuando alguien te cuenta un problema?")
print("1. Intento hacerlo reír")
print("2. Le doy consejos y soluciones")
print("3. Lo escucho y le doy apoyo emocional")
p13 = pedir_respuesta()

#Pregunta 14 y sus alternativas:
print("14) ¿Qué tan puntual eres?")
print("1. Llego justo a la hora")
print("2. Llego tarde")
print("3. Siempre llego antes de tiempo")
p14 = pedir_respuesta()

#Pregunta 15 y sus alternativas:
print("15) ¿Qué red social utilizas más?")
print("1. Tiktok")
print("2. Instagram")
print("3. Twitter")
p15 = pedir_respuesta()

#Pregunta 16 y sus alternativas:
print("16) Cuando te gusta alguien...")
print("1. Huyo")
print("2. Se lo digo de frente")
print("3. Me pongo nervios@")
p16 = pedir_respuesta()

#Pregunta 17 y sus alternativas:
print("17) ¿Qué genero musical prefieres?")
print("1. Reggeaton")
print("2. Rock")
print("3. Pop")
p17 = pedir_respuesta()

#Pregunta 18 y sus alternativas:
print("18) ¿Qué tan ordenado eres?")
print("1. Medianamente ordenado")
print("2. Para nada ordenado")
print("3. Muy ordenado")
p18 = pedir_respuesta()

#Pregunta 19 y sus alternativas:
print("19) ¿Cuál es tu comida favorita?")
print("1. Hamburguesa")
print("2. Pizza")
print("3. Sushi")
p19 = pedir_respuesta()

#Pregunta 20 y sus alternativas:
print("20) ¿Qué tan romantico eres?")
print("1. Normal")
print("2. Poco")
print("3. Muchísimo")
p20 = pedir_respuesta()

#Pregunta 21 y sus alternativas:
print("21) ¿Cuál es tu estación favorita?")
print("1. Verano")
print("2. Invierno/Otoño")
print("3. Primavera")
p21 = pedir_respuesta()

#Pregunta 22 y sus alternativas:
print("22) ¿Qué tan llorón eres?")
print("1. Poco")
print("2. Casi nada")
print("3. Mucho")
p22 = pedir_respuesta()

#Pregunta 23 y sus alternativas:
print("23) Si tuvieras un superpoder, ¿cuál eligirías?")
print("1. Leer mentes")
print("2. Supervelocidad")
print("3. Curar personas")
p23 = pedir_respuesta()

#Pregunta 24 y sus alternativas:
print("24) ¿Cuál es tu bebida favorita?")
print("1. Gaseosa")
print("2. Té")
print("3. Agua")
p24 = pedir_respuesta()

#Pregunta 25 y sus alternativas:
print("25) ¿Qué gastronomía es tu favorita?")
print("1. Japonesa")
print("2. Peruana")
print("3. Mexicana")
p25 = pedir_respuesta()

#Pregunta 26 y sus alternativas:
print("26) ¿Cuál sería tu trabajo soñado?")
print("1. Influencer")
print("2. Empresario")
print("3. Artista")
p26 = pedir_respuesta()

#Pregunta 27 y sus alternativas:
print("27) ¿Cómo gastas tu dinero?")
print("1. Lo invierto")
print("2. Lo ahorro")
print("3. Lo gasto sin pensar")
p27 = pedir_respuesta()

#Pregunta 28 y sus alternativas:
print("28) ¿Te consideras una persona más lógica o más emocional?")
print("1. Un poco de ambos")
print("2. Lógica")
print("3. Emocional")
p28 = pedir_respuesta()

#Pregunta 29 y sus alternativas:
print("29) ¿Cómo prefieres recargar tu energía después de un día cansado?")
print("1. Meditación")
print("2. Dormir")
print("3. Ejercitarme")
p29 = pedir_respuesta()

#Pregunta 30 y sus alternativas:
print("30) ¿En qué momento del día prefieres hacer las cosas?")
print("1. En la tarde")
print("2. En la noche")
print("3. En la mañana")
p30 = pedir_respuesta()

#Pregunta 31 y sus alternativas:
print("31) Si fueses un animal ¿cuál serías?")
print("1. Perro")
print("2. Gato")
print("3. Conejo")
p31 = pedir_respuesta()

#Pregunta 32 y sus alternativas:
print("32) ¿Sueles enfadarte con facilidad?")
print("1. Depende de la situación")
print("2. No")
print("3. Sí")
p32 = pedir_respuesta()

#Pregunta 33 y sus alternativas:
print("33) Para tí, ¿qué es el arte?")
print("1. Cualquier creación propia sin importar el significado")
print("2. Una forma compleja de expresar nuestra identidad")
print("3. Un balance entre la realidad y la fantasía")
p33 = pedir_respuesta()

#Pregunta 34 y sus alternativas:
print("34) ¿Con quién de tu familia sueles apoyarte más?")
print("1. Madre")
print("2. Padre")
print("3. Hermanos")
p34 = pedir_respuesta()

#Pregunta 35 y sus alternativas:
print("35) ¿Cuál es tu polinesio favorito?")
print("1. Rafael")
print("2. Karen")
print("3. Lesslie")
p35 = pedir_respuesta()

#Suma de todas las respuestas:
suma = p1 + p2 + p3 + p4 + p5 + p6 + p7 + p8 + p9 + p10 + p11 + p12 + p13 + p14 + p15 + p16 + p17 + p18 + p19 + p20 + p21 + p22 + p23 + p24 + p25 + p26 + p27 + p28 + p29 + p30 + p31 + p32 + p33 + p34 + p35

#Si la suma sale entre 35-58, eres Rafa y saldrá una imagen + descripción de su personalidad
#Si la suma sale entre 59-81, eres Karen y saldrá una imagen + descripción de su personalidad
#Si la suma sale entre 82-105, eres Lesslie y saldrá una imagen + descripción de su personalidad

import requests
from PIL import Image
from io import BytesIO
from IPython.display import display

#
link_rafa = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcU8LpRGXHs8XasZjgZpZxrbMgaGD1Lr2_TPtoBjGMMU99qavdGz7pPxc&s=10"
link_karen = "https://static.wikia.nocookie.net/wiki-random/images/6/6f/50b5682a0bf73c375857bfc030f0ff747db9dc94_00.jpg/revision/latest?cb=20180703003459&path-prefix=es"
link_less = "https://i.pinimg.com/736x/54/26/de/5426de3c1929269521bb22deeb4032a2.jpg"

# PASO 2: La computadora de Google viaja por internet a buscar las fotos
foto_rafa = Image.open(BytesIO(requests.get(link_rafa).content))
foto_karen = Image.open(BytesIO(requests.get(link_karen).content))
foto_less = Image.open(BytesIO(requests.get(link_less).content))

if 35 <= suma <= 58:
    print("¡Eres Rafa!")
    display(foto_rafa)
    print("Tienes una personalidad ruidosa, impulsiva y sumamente cómica, convirtiéndote siempre en el alma impredecible de cualquier grupo. Lejos de ser alguien serio, eres el más loco y desatado, el responsable de las bromas más pesadas, las ocurrencias extremas y de buscar la adrenalina en dinámicas intensas o deportes extremos. Tu estilo de humor es irreverente, directo y sin filtros, al punto de que muchas veces rozas lo polémico y te ganas la reputación de ser el más funable por decir lo que piensas sin medir las consecuencias. Eres un espíritu libre que prefiere la diversión espontánea antes que la rigidez, aportando siempre esa chispa de caos que rompe por completo con la normalidad.")
elif 59 < suma <= 81:
    print("¡Eres Karen!")
    display(foto_karen)
    print("Tienes una personalidad sumamente auténtica, magnética y llena de contrastes fascinantes. No necesitas buscar riesgos físicos innecesarios ni te llaman la atención los deportes extremos; de hecho, eres alguien bastante dormilón que disfruta enormemente de un buen descanso. Tu verdadera fuerza radica en una mente brillante y una tremenda seguridad en ti mismo, siendo el perfil más analítico de los tres hermanos, aunque a veces tu mente procesa tantas cosas a la vez que pareces una persona un poco distraída o despistada en el día a día. Tu esencia es una mezcla única de un espíritu hippie —relajado, amante de la libertad, la paz y el arte— con una actitud punk, manteniéndote firme en tus convicciones, defendiendo tu individualidad y rompiendo con las reglas tradicionales sin temor al qué dirán.")
elif 82 < suma <= 105:
    print("¡Eres Lesslie!")
    display(foto_less)
    print("Tienes una personalidad que destaca por ser el corazón emotivo, dulce y equilibrado de tu entorno. Eres una persona sumamente sensible y empática, capaz de construir vínculos de confianza profundos y cercanos con los demás gracias a tu calidez y autenticidad. A pesar de tener una esencia soñadora y muy creativa, demuestras un crecimiento constante hacia la madurez, asumiendo las responsabilidades de la vida con gran sensatez y templanza. Te conviertes de forma natural en el pilar afectivo que abraza, cuida y protege a tus seres queridos, combinando esa ternura innata con una fuerza interior protectora que te hace el refugio seguro de quienes te rodean.")

print("FIN")

"""#8
Reviso que el código tiene una idea clara y entretenida: propone un test de personalidad con 12 preguntas, suma las respuestas y entrega un resultado final con descripción e imagen. Valoro que las preguntas estén ordenadas, que las alternativas sean comprensibles y que se haya intentado complementar el resultado con imágenes, lo cual mejora la presentación del proyecto. Sin embargo, el programa tiene errores importantes que pueden impedir que funcione. Primero, se define la imagen como `imagen_leslie`, pero luego se usa `imagen_less`, por lo que el código puede fallar con un error de variable no definida. Además, las rutas de las imágenes empiezan con `/`, lo que puede causar problemas si los archivos no están exactamente en esa ubicación. También el caso en que la suma sea exactamente 12 no recibe ningún resultado, aunque es un puntaje posible. Otro aspecto a mejorar es que no se validan las respuestas del usuario: si escribe texto o un número fuera de 1 a 3, el programa puede fallar o dar un resultado incorrecto. En general, considero que la propuesta es creativa y está bastante desarrollada en contenido, pero necesita corregir errores de variables, rutas de archivos y validación para funcionar correctamente de principio a fin.

"""

